name=XbeeWrapper
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Wraps an XBee radio.
paragraph=Presents an API for Xbee control to be compatible with other radios.
category=Communication
url=http://10.42.0.1:3000/GameOfDrones/sensor-network/libraries/Rf69Wrapper
architectures=*
depends=XBee-Arduino library (0.6.0), AltSoftSerial (1.4.0)