name=UltrasonicSensor
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Generates packets from ultrasonic sensor readings.
category=Communication
url=https://spork.fusion.navy.mil/game-of-drones/sensors/sensor-network/libraries/UltrasonicSensor
architectures=*
depends=PacketTypes, Ultrasonic