name=GuiConnection
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Handles communication between arduino and GUI.
paragraph=Used specifically on the coordinator device which is connected to the GUI via serial.
category=Communication
url=https://spork.fusion.navy.mil/game-of-drones/sensors/sensor-network/libraries/GuiConnection
architectures=*
depends=PacketSerial (1.4.0), PacketTypes