name=SensorNetworkRadio
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Defines a radio wrapper for GoD sensor use cases.
paragraph=Wrapper allows registering handlers for known packet types.
category=Communication
url=http://10.42.0.1:3000/GameOfDrones/sensor-network/libraries/SensorNetworkRadio
architectures=*
depends=RadioHead