name=SensorNetworkRadio
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Defines packet type bytes for the GoD sensor network.
paragraph=Allows devices using this library to match packet types to each other.
category=Communication
url=http://10.42.0.1:3000/GameOfDrones/sensor-network/libraries/SensorNetworkRadio
architectures=*