name=Rf69Wrapper
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Wraps a RadioHead RH_RF69 radio.
paragraph=Presents an identical API for different radios for compatibility.
category=Communication
url=http://10.42.0.1:3000/GameOfDrones/sensor-network/libraries/Rf69Wrapper
architectures=*
depends=RadioHead (1.143.1)