name=PhotodiodeJammer
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Blocks jammable packets when a LASER with the right frequency hits the photodiode array.
category=Communication
url=https://spork.fusion.navy.mil/game-of-drones/sensors/sensor-network/libraries/PhotodiodeJammer
architectures=*
