name=Rf69Radio
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Handles communication between devices using Rf69 radios.
category=Communication
url=https://spork.fusion.navy.mil/game-of-drones/sensors/sensor-network/libraries/Rf69Radio
architectures=*
depends=RadioHead (1.143.1)