name=JammerButton
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Generates packets when jammer button is pressed.
category=Communication
url=https://spork.fusion.navy.mil/game-of-drones/sensors/sensor-network/libraries/JammerButton
architectures=*
depends=PacketTypes