# This file is currently unused because arduino-cli does not
# support both the --libraries tag and a sketch.yaml. Once
# arduino-cli reaches version 1.3+, this file should be
# renamed to "sketch.yaml" and the --libraries option and
# other options should no longer be used in "arduino-cli compile".
# Even when usused, this file should still be maintained to
# assist with finding sketch info for development and to
# prepare for the future
profiles:
  uno:
    fqbn: arduino:avr:uno
    platforms:
      - platform: arduino:avr (1.8.6)
    libraries:
      - RadioHead (1.143.1)
      - dev: ../libraries/SensorNetworkRadio (1.0.0)
default_profile: uno
