name=XbeeRadio
version=1.0.0
author=William Black (william.s.black48.civ@us.navy.mil)
sentence=Handles communication over an XBee network.
paragraph=Used both for sending and receiving.
category=Communication
url=https://spork.fusion.navy.mil/game-of-drones/sensors/sensor-network/libraries/XbeeRadio
architectures=*
depends=XBee-Arduino Library, AltSoftSerial
